### ISSUE TITLE
`ghorg examples` are failing

### ISSUE THREAD

**Issue by vlcinsky** [gabrie30/ghorg#336]
**Describe the bug**
- `ghorg examples` prints something, but the output includes "panic: runtime error" message
- `ghorg examples github` prints only "Only supported SCM providers are available for examples, please use one of the following: github, gitlab, bitbucket, or gitea"

**To Reproduce**
```shell
$ ghorg examples
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/gabrie30/ghorg/cmd.examplesFunc(0x18cfe60?, {0x1913be8?, 0x0?, 0x0?})
        /Users/jay.gabriels/go/src/github.com/gabrie30/ghorg/cmd/examples.go:20 +0xf3
github.com/spf13/cobra.(*Command).execute(0x18cfe60, {0x1913be8, 0x0, 0x0})
        /Users/jay.gabriels/go/src/github.com/gabrie30/ghorg/vendor/github.com/spf13/cobra/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x18d09e0)
        /Users/jay.gabriels/go/src/github.com/gabrie30/ghorg/vendor/github.com/spf13/cobra/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/jay.gabriels/go/src/github.com/gabrie30/ghorg/vendor/github.com/spf13/cobra/command.go:992
github.com/gabrie30/ghorg/cmd.Execute()
        /Users/jay.gabriels/go/src/github.com/gabrie30/ghorg/cmd/root.go:331 +0x25
main.main()
        /Users/jay.gabriels/go/src/github.com/gabrie30/ghorg/main.go:8 +0x17
```
Note the first printed line with "panic: ..."

```shell
$ ghorg examples github
Only supported SCM providers are available for examples, please use one of the following: github, gitlab, bitbucket, or gitea
```
The same output is printed for github, gitlab, bitbucket, or gitea

Tested with ghorg version v1.9.8.

**Comment by gabrie30** [comment]
Thank you @vlcinsky!

**Comment by vlcinsky** [comment]
Great. I appreciate how extensive the examples are.
